[package]
name = "fortune-rs"
version = "0.1.0"
edition = "2021"
default-run = "fortune"

[dependencies]
anyhow = "1.0"
assert_cmd = "2.0.16"
clap = { version = "4.4", features = ["derive"] }
glob = "0.3"
rand = "0.8"
regex = "1.10"

[[bin]]
name = "fortune"
path = "src/main.rs"

[[bin]]
name = "strfile"
path = "src/strfile.rs"

