[package]
name = "fortune-rs"
version = "0.1.0"
edition = "2021"
default-run = "fortune"

[dependencies]
rand = "0.8"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }

[[bin]]
name = "fortune"
path = "src/main.rs"

[[bin]]
name = "strfile"
path = "src/strfile.rs"

